/**:
  ros__parameters:
    sensor_type: "icm20948"
    i2c_device: "/dev/i2c-7"
    i2c_addr: 0x68
    frame_id: "imu_link"
    rate_hz: 80

    accel_range_g: 2
    gyro_range_dps: 2000
    gyro_scale_z: 1.00515
    auto_calibrate_gyro: true

    # These values should be filled after running calibrate_gyro
    gyro_bias_x: 0.0191729
    gyro_bias_y: 0.0105967
    gyro_bias_z: 0.00168618

    accel_bias_x: 0.0
    accel_bias_y: 0.0
    accel_bias_z: 0.0

    # Covariance diagonals (x, y, z)
    accel_covariance: [0.00365912, 0.00144280, 0.00471530]
    gyro_covariance: [0.00001598, 0.00000726, 0.00000663]
